### ISSUE TITLE
非HTTP文件传输方案

### ISSUE THREAD

**Issue by KawaiiZapic** [BalloonUpdate/Docs#5]
如题, 国内机房大多阻断HTTP以及HTTPS服务, 作为服主没有理由也没有必要去做备案什么的, 特别麻烦资质也不一定能过.  
所以需要一种非HTTP协议的文件传输方案去规避这种阻断, 不知道贵项目有没有这种想法.

**Comment by asforest** [comment]
会给Jar客户端增加sftp协议的支持。支持密码和秘钥访问，同时也会保持对http协议的共存
